### ISSUE TITLE
Conflict wit UserDefinedForm

### ISSUE THREAD

**Issue by dacar** [mateusz/silverstripe-frontend#14]
After enabling PJAX i get the following fatal error: 

[05-Jul-2013 13:34:33 Europe/Berlin] PHP Fatal error:  Class 'SS_LogErrorFileFormatter' not found inSilverstripe/userforms/code/model/UserDefinedForm.php on line 1052

The error is forced by this block: 

```
public function index($request) {
    $controller = $this;
    $responseNegotiator = new PjaxResponseNegotiator(
        array(
            'PagePagination' => function() use(&$controller) {
                return $controller->renderWith('Page_Pagination');
            },
            'default' => function() use(&$controller) {
                return $controller->render();
            }
        ),
        $this->response
    );
    return $responseNegotiator->respond($request);
}
```

**Comment by mateusz** [comment]
@dacar Hey man, sorry for late response, missed Github notification. I hope you managed to sort it out since then - it does look to me like a mismatch in module versions, or a flush might be needed - just retested with latest userforms and all seems to be ok.

If you still stuck, let me know - got the notifications hopefully sorted now :-)

**Comment by mateusz** [comment]
Will close this, reopen if you find this is still a problem!
