### ISSUE TITLE
Packagist support

### ISSUE THREAD

**Issue by ARNHOE** [mateusz/silverstripe-frontend#16]
Any chance to have this on Packagist? Really frustrating to not being able to pick up any changes through composer update like framework/cms/googlesitemaps etc do.

**Comment by mateusz** [comment]
Hmm it has always been there, just recently [renamed](https://packagist.org/packages/mateusz/frontend) because @chillu raised an issue that I shouldn't use the silverstripe namespace for my private modules ;-) Add the following line to your composer.json:

`"mateusz/frontend": "*"`

Legacy "silverstripe/frontend" should work as well. I've updated the [readme](https://github.com/mateusz/silverstripe-frontend/blob/master/Readme.md) installation instructions to reflect all that.

**Comment by ARNHOE** [comment]
Hmpf, I searched for mateusz on Packagist and didn't found it. But good to see its on there, thanks!

**Comment by mateusz** [comment]
Packagist search... meh. Somehow it shows the most popular things on top, and sometimes omits results. The fix would be to get this module very popular so it comes up on top ;-)
